
export const NarrationEducatingMessagesMap = {
    "DUP PASSBOOK CHG": "Charges for issuing duplicate passbook/ statement.",
    "CHG FOR ONUS WDL": "Charges for cash withdrawal per transaction in Indian bank ATMs and other bank ATMs for SB and CA",
    "ATM WDL CHARGES": "Charges for cash withdrawal per transaction in Indian bank ATMs and other bank ATMs for SB and CA",
    "ATM ENQ CHARGES": "Charges for cash withdrawal per transaction in Indian bank ATMs and other bank ATMs for SB and CA",
    "ATM INSUFFICIENT FUNDS CHARGES": "Withdrawal transaction decline due to insufficient balance through ATM/ BNAs",
    "ATM _Card _Issuance_ Fe": "Membership fee for ATM card",
    "DUP CARD": "ATM/ Debit card replacement charges",
    "ATM AMC CHGS": "Annual Maintenance Charges ATM card",
    "CHG FOR ATM ONUS DEP": "Cash deposit charges through ATM/cash recyclers(BNA)",
    "CHQ DISHONOUR": "Cheque return charges",
    "ACH RTN CHRGS": "ECS Debit return charges",
    "NEFT Charge": "NEFT charges",
    "RGTS Charge": "RTGS charges",
    "IMPS Charge": "IMPS charges",
    "SI Charge": "Standing instruction charges",
    "Cash handling charges": "Cash handling charges",
    "SMS_ CHGS_": "SMS alert charges",
    "MIN BAL CHGS": "Non maintenance of minimum balance charges in SB/ CA",
    "LOCKER RENT": "Rent on locker",
    "Cash deposit chrages other": "Cash deposit chrages at Non-home branch",
    "Mandate Reg Chgs": "ECS mandate registration charges",
    "UNCOLL CHRG DT": "Uncollected charges",
    "Folio Charges -Txn": "Account keeping charges",
    "Excess wdl charges": "Excess withdrawal charges"
}