
export const NarrationEducatingMessagesMap = {
    "DUP PASSBOOK CHG": "Charges for issuing duplicate passbook/ statement.",
    "CHG FOR ONUS WDL": "Charges for cash withdrawal per transaction in Indian bank ATMs and other bank ATMs for SB and CA",
    "ATM WDL CHARGES": "Charges for cash withdrawal per transaction in Indian bank ATMs and other bank ATMs for SB and CA",
    "ATM ENQ CHARGES": "Charges for cash withdrawal per transaction in Indian bank ATMs and other bank ATMs for SB and CA",
    "ATM INSUFFICIENT FUNDS CHARGES": "Withdrawal transaction decline due to insufficient balance through ATM/ BNAs",
    "ATM _Card _Issuance_ Fe": "Membership fee for ATM card",
    "DUP CARD": "ATM/ Debit card replacement charges",
    "ATM AMC CHGS": "Annual Maintenance Charges ATM card",
    "CHG FOR ATM ONUS DEP": "Cash deposit charges through ATM/cash recyclers(BNA)",
    "CHQ DISHONOUR": "Cheque return charges",
    "ACH RTN CHRGS": "ECS Debit return charges",
    "NEFT Charge": "NEFT charges",
    "RGTS Charge": "RTGS charges",
    "IMPS Charge": "IMPS charges",
    "SI Charge": "Standing instruction charges",
    "Cash handling charges": "Cash handling charges",
    "SMS_ CHGS_": "SMS alert charges",
    "MIN BAL CHGS": "Non maintenance of minimum balance charges in SB/ CA",
    "LOCKER RENT": "Rent on locker",
    "Cash deposit chrages other": "Cash deposit chrages at Non-home branch",
    "Mandate Reg Chgs": "ECS mandate registration charges",
    "UNCOLL CHRG DT": "Uncollected charges",
    "Folio Charges -Txn": "Account keeping charges",
    "Excess wdl charges": "Excess withdrawal charges"
}

// export enum Narration {
//     DUP_PASSBOOK_CHG = "DUP PASSBOOK CHG",
//     CHG_FOR_ONUS_WDL = "CHG FOR ONUS WDL",
//     ATM_WDL_CHARGES = "ATM WDL CHARGES",
//     ATM_ENQ_CHARGES = "ATM ENQ CHARGES",
//     ATM_INSUFFICIENT_FUNDS_CHARGES = "ATM INSUFFICIENT FUNDS CHARGES",
//     ATM_CARD_ISSUANCE_FE = "ATM _Card _Issuance_ Fe",
//     DUP_CARD = "DUP CARD",
//     ATM_AMC_CHGS = "ATM AMC CHGS",
//     CHG_FOR_ATM_ONUS_DEP = "CHG FOR ATM ONUS DEP",
//     CHQ_DISHONOUR = "CHQ DISHONOUR",
//     ACH_RTN_CHRGS = "ACH RTN CHRGS",
//     NEFT_CHARGE = "NEFT Charge",
//     RGTS_CHARGE = "RGTS Charge",
//     IMPS_CHARGE = "IMPS Charge",
//     SI_CHARGE = "SI Charge",
//     CASH_HANDLING_CHARGES = "Cash handling charges",
//     SMS_CHGS = "SMS_ CHGS_",
//     MIN_BAL_CHGS = "MIN BAL CHGS",
//     LOCKER_RENT = "LOCKER RENT",
//     CASH_DEPOSIT_CHARGES_OTHER = "Cash deposit charges other",
//     MANDATE_REG_CHGS = "Mandate Reg Chgs",
//     UNCOLL_CHRG_DT = "UNCOLL CHRG DT",
//     FOLIO_CHARGES_TXN = "Folio Charges -Txn",
//     EXCESS_WDL_CHARGES = "Excess wdl charges"
// }